### ISSUE TITLE
Script Error?

### ISSUE THREAD

**Issue by lizlefae** [hamstap85/FirebotQueue#1]
Hi, I installed this script and it failed to work as expected, i am including the error from my firebot log below
``19:11:03 GMT-0400 (Eastern Daylight Time) - error: [v5.53.2] Error while running script 'queue.js' 
{
  message: "Cannot read property 'userCommand' of undefined",
  stack: "TypeError: Cannot read property 'userCommand' of undefined\n" +
    '    at Object.run (C:\\Users\\user\\AppData\\Roaming\\Firebot\\v5\\profiles\\Main Profile\\scripts\\queue.js:1:17629)\n' +
    '    at executeScript (C:\\Users\\user\\AppData\\Local\\firebotv5\\app-5.53.2\\resources\\app.asar\\backend\\common\\handlers\\custom-scripts\\custom-script-runner.js:87:69)\n' +
    '    at runStartUpScript (C:\\Users\\user\\AppData\\Local\\firebotv5\\app-5.53.2\\resources\\app.asar\\backend\\common\\handlers\\custom-scripts\\custom-script-runner.js:173:15)\n' +
    '    at Object.runStartupScripts (C:\\Users\\user\\AppData\\Local\\firebotv5\\app-5.53.2\\resources\\app.asar\\backend\\common\\handlers\\custom-scripts\\startup-scripts-manager.js:106:15)\n' +
    '    at Object.<anonymous> (C:\\Users\\user\\AppData\\Local\\firebotv5\\app-5.53.2\\resources\\app.asar\\backend\\app-management\\electron\\window-management.js:220:31)\n' +
    '    at Object.emit (events.js:327:22)'
}``

**Comment by giff-h** [comment]
Hi I just now saw this, it's been kind of left alone because of no new needed features, I'll try to dust off the code locally and see if I can reproduce. I've been a bit burned out on personal projects though, I'll try my best to get to it.
